export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_PROFILE = 'GET_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const GET_ADDRESS = 'GET_ADDRESS';
export const GET_DATA = 'GET_DATA';
export const GET_DATA_GURU = 'GET_DATA_GURU';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const CHECKOUT_PESANAN = 'CHECKOUT_PESANAN';
export const CHANGE_STATUS_CHECKOUT_PESANAN = 'CHANGE_STATUS_CHECKOUT_PESANAN';
export const UPDATE_PESANAN = 'UPDATE_PESANAN';
export const NOTIFIKASI = 'NOTIFIKASI';
export const UPDATE_NOTIFIKASI = 'UPDATE_NOTIFIKASI';
export const DELETE_NOTIFIKASI = 'DELETE_NOTIFIKASI';
export const GET_DATA_CONVERSATION = 'GET_DATA_CONVERSATION';
export const GET_DATA_MESSAGE = 'GET_DATA_MESSAGE';

export const USER_GURU = 'USER_GURU';

export const ADD_CART = 'ADD_CART';
export const DELETE_CART = 'DELETE_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const GET_DATA_HARGA = 'GET_DATA_HARGA';
